import random
import string

if __name__ == '__main__':
    usernames = [
        'sugarcravings76',
        'vanilladreams48',
        'doughydelights29',
        'creampuff91',
        'cocoalicious12',
        'bakersparadise83',
        'cookiecrumble57',
        'frostyfantasy18',
        'pastryperfection42',
        'yummysweettooth66',
        'biscuitbliss23',
        'cinnamonsugar79',
        'whippedcream45',
        'crispyconfections31',
        'meltinyourmouth53',
        'sweetbreadheaven67',
        'chocolatelover92',
        'artisanalbakes24',
        'berrylicious11',
        'flakygoodness35',
        'cupcakewizard76',
        'crunchycroissant19',
        'sprinkledelight44',
        'savourybakes61',
        'dreamycakes57',
        'sugaryindulgence22',
        'sconesandjam33',
        'wholesomegoodies75',
        'butterybrioche99',
        'cakedecorator27',
        'puffpastrypalace48',
        'deliciousdoughnuts62',
        'gingerbreadmagic87',
        'swirlycinnamon39',
        'batterandwhisk58',
        'frenchpastrylove66',
        'crustybaguettes83',
        'cupcakeaddict14',
        'sweetandsavory41',
        'artisanbaker12',
        'sugarcoatedbliss23',
        'fluffypancakes57',
        'bakeaholic92',
        'divineconfections36',
        'vanillabeanparadise81',
        'delightfuldesserts19',
        'creamycaramel55',
        'crumblytreats73',
        'doughlicious28',
        'cookiejarwonders41',
        'irresistiblepastries97',
        'bakeryenthusiast14',
        'sugarglazeddonuts29',
        'sweetsensation79',
        'pieperfection42',
        'cookiecravings56',
        'muffinlover21',
        'chocolatechipdreams88',
        'whiskmeaway39',
        'cupcaketemptation64',
        'sugarandspice96',
        'pastryprince19',
        'flavorfulcreations33',
        'bakefromtheheart27',
        'sconefantasy72',
        'frostingdelight45',
        'breadlovers88',
        'sweettoothfairy31',
        'confectionerymagic57',
        'doughnutparadise14',
        'dreamycustards82',
        'bakeryqueen29',
        'cakewalk55',
        'cookieartisan76',
        'artisanalmaster21',
        'pastrylovebug48',
        'creamfilledjoy18',
        'croissantcraver65',
        'cupofcake92',
        'sugarcravings87',
        'vanilladreams62',
        'doughydelights13',
        'creampuff45',
        'cocoalicious78',
        'bakersparadise92',
        'cookiecrumble27',
        'frostyfantasy59',
        'pastryperfection11',
        'yummysweettooth26',
        'biscuitbliss77',
        'cinnamonsugar38',
        'whippedcream54',
        'crispyconfections19',
        'meltinyourmouth63',
        'sweetbreadheaven41',
        'chocolatelover96',
        'artisanalbakes73',
        'berrylicious28',
        'flakygoodness51',
        'cupcakewizard47',
        'crunchycroissant12',
        'sprinkledelight69',
        'savourybakes32',
        'dreamycakes82',
        'sugaryindulgence44',
        'sconesandjam97',
        'wholesomegoodies26',
        'butterybrioche58',
        'cakedecorator83',
        'puffpastrypalace66',
        'deliciousdoughnuts39',
        'gingerbreadmagic16',
        'swirlycinnamon91',
        'batterandwhisk36',
        'frenchpastrylove72',
        'crustybaguettes17',
        'cupcakeaddict42',
        'sweetandsavory73',
        'artisanbaker98',
        'sugarcoatedbliss15',
        'fluffypancakes39',
        'bakeaholic84',
        'divineconfections71',
        'vanillabeanparadise47',
        'delightfuldesserts23',
        'creamycaramel67',
        'crumblytreats29',
        'doughlicious62',
        'cookiejarwonders83',
        'irresistiblepastries48',
        'bakeryenthusiast17',
        'sugarglazeddonuts94',
        'sweetsensation61',
        'pieperfection27',
        'cookiecravings56',
        'muffinlover12',
        'chocolatechipdreams87',
        'whiskmeaway42',
        'cupcaketemptation79',
        'sugarandspice32',
        'pastryprince77',
        'flavorfulcreations55',
        'bakefromtheheart18',
        'sconefantasy93',
        'frostingdelight76',
        'breadlovers29',
        'sweettoothfairy64',
        'confectionerymagic12',
        'doughnutparadise38',
        'dreamycustards77',
        'bakeryqueen23',
        'cakewalk58',
        'cookieartisan82',
        'artisanalmaster47',
        'pastrylovebug79',
        'creamfilledjoy34',
        'croissantcraver19',
        'cupofcake62',
        'sugarcravings88',
        'vanilladreams63',
        'doughydelights14',
        'creampuff46',
        'cocoalicious79',
        'bakersparadise93',
        'cookiecrumble28',
        'frostyfantasy60',
        'pastryperfection12',
        'yummysweettooth27',
        'biscuitbliss78',
        'cinnamonsugar39',
        'whippedcream55',
        'crispyconfections20',
        'meltinyourmouth64',
        'sweetbreadheaven42',
        'chocolatelover97',
        'artisanalbakes74',
        'berrylicious29',
        'flakygoodness52',
        'cupcakewizard48',
        'crunchycroissant13',
        'sprinkledelight70',
        'savourybakes33',
        'dreamycakes83',
        'sugaryindulgence45',
        'sconesandjam98',
        'wholesomegoodies27',
        'butterybrioche59',
        'cakedecorator84',
        'puffpastrypalace67',
        'deliciousdoughnuts40',
        'gingerbreadmagic17',
        'swirlycinnamon92',
        'batterandwhisk37',
        'frenchpastrylove73',
        'crustybaguettes18',
        'cupcakeaddict43',
        'sweetandsavory74',
        'artisanbaker99',
        'sugarcoatedbliss16',
        'fluffypancakes40',
        'bakeaholic85',
        'divineconfections72',
        'vanillabeanparadise48',
        'delightfuldesserts24',
        'creamycaramel68',
        'crumblytreats30',
        'doughlicious63',
        'cookiejarwonders84',
        'irresistiblepastries49',
        'bakeryenthusiast18',
        'sugarglazeddonuts95',
        'sweetsensation62',
        'pieperfection28',
        'cookiecravings57',
        'muffinlover13',
        'chocolatechipdreams88',
        'whiskmeaway43',
        'cupcaketemptation80',
        'sugarandspice33',
        'pastryprince78',
        'flavorfulcreations56',
        'bakefromtheheart19',
        'sconefantasy94',
        'frostingdelight77',
        'breadlovers30',
        'sweettoothfairy65',
        'confectionerymagic13',
        'doughnutparadise39',
        'dreamycustards78',
        'bakeryqueen24',
        'cakewalk59',
        'cookieartisan83',
        'artisanalmaster48',
        'pastrylovebug80',
        'creamfilledjoy35',
        'croissantcraver20',
        'cupofcake63',
        'sugarcravings89',
        'vanilladreams64',
        'doughydelights15',
        'creampuff47',
        'cocoalicious80',
        'bakersparadise94',
        'cookiecrumble29',
        'frostyfantasy61',
        'pastryperfection13',
        'yummysweettooth28',
        'biscuitbliss79',
        'cinnamonsugar40',
        'whippedcream56',
        'crispyconfections21',
        'meltinyourmouth65',
        'sweetbreadheaven43',
        'chocolatelover98',
        'artisanalbakes75',
        'berrylicious30',
        'flakygoodness53',
        'cupcakewizard49',
        'crunchycroissant14',
        'sprinkledelight71',
        'savourybakes34',
        'dreamycakes84',
        'sugaryindulgence46',
        'sconesandjam99',
        'wholesomegoodies28',
        'butterybrioche60',
        'cakedecorator85',
        'puffpastrypalace68',
        'deliciousdoughnuts41',
        'gingerbreadmagic18',
        'swirlycinnamon93',
        'batterandwhisk38',
        'frenchpastrylove74',
        'crustybaguettes19',
        'cupcakeaddict44',
        'sweetandsavory75',
        'artisanbaker100',
        'sugarcoatedbliss17',
        'fluffypancakes41',
        'bakeaholic86',
        'divineconfections73',
        'vanillabeanparadise49',
        'delightfuldesserts25',
        'creamycaramel69',
        'crumblytreats31',
        'doughlicious64',
        'cookiejarwonders85',
        'irresistiblepastries50',
        'bakeryenthusiast19',
        'sugarglazeddonuts96',
        'sweetsensation63',
        'pieperfection29',
        'cookiecravings58',
        'muffinlover14',
        'chocolatechipdreams89',
        'whiskmeaway44',
        'cupcaketemptation81',
        'sugarandspice34',
        'pastryprince79',
        'flavorfulcreations57',
        'bakefromtheheart20',
        'sconefantasy95',
        'frostingdelight78',
        'breadlovers31',
        'sweettoothfairy66',
        'confectionerymagic14',
        'doughnutparadise40',
        'dreamycustards79',
        'bakeryqueen25',
        'cakewalk60',
        'cookieartisan84',
        'artisanalmaster49',
        'pastrylovebug81',
        'creamfilledjoy36',
        'croissantcraver21',
        'cupofcake64',
        'sugarcravings90',
        'vanilladreams65',
        'doughydelights16',
        'creampuff48',
        'cocoalicious81',
        'bakersparadise95',
        'cookiecrumble30',
        'frostyfantasy62',
        'pastryperfection14',
        'yummysweettooth29',
        'biscuitbliss80',
        'cinnamonsugar41',
        'whippedcream57',
        'crispyconfections22',
        'meltinyourmouth66',
        'sweetbreadheaven44',
        'chocolatelover99',
        'artisanalbakes76',
        'berrylicious31',
        'flakygoodness54',
        'cupcakewizard50',
        'crunchycroissant15',
        'sprinkledelight72',
        'savourybakes35',
        'dreamycakes85',
        'sugaryindulgence47',
        'sconesandjam100',
        'wholesomegoodies29',
        'butterybrioche61',
        'cakedecorator86',
        'puffpastrypalace69',
        'deliciousdoughnuts42',
        'gingerbreadmagic19',
        'swirlycinnamon94',
        'batterandwhisk39',
        'frenchpastrylove75',
        'crustybaguettes20',
        'cupcakeaddict45',
        'sweetandsavory76',
        'artisanbaker101',
        'sugarcoatedbliss18',
        'fluffypancakes42',
        'bakeaholic87',
        'divineconfections74',
        'vanillabeanparadise50',
        'delightfulcake69'
    ]

    print('INSERT INTO users VALUES ')
    for name in usernames:
        hash = ''
        for i in range(45):
            hash += random.choice(string.ascii_letters)
        coma = ''
        if name != usernames[-1]:
            coma = ','
        print('(DEFAULT, \'' + name + '\', \'' + hash
              + '\', current_timestamp-\'' + str(random.randint(2, 100)) + ' hours ' + str(random.randint(2, 60)) + ' minutes\'::interval)' + coma)
    print(';')

    print('INSERT INTO users_liked VALUES ')
    for i in range(1, 364):
        recipes = list(range(1, 103))
        n = random.randint(1, 100)
        for j in range(n):
            recipe = random.choice(recipes)
            recipes.remove(recipe)
            coma = ''
            if i != 363 or j != n-1:
                coma = ','
            print('(' + str(recipe) + ', ' + str(i) + ')' + coma)
    print(';')

    comments = [
        "This recipe is amazing! It's now my go-to for all baking needs.",
        "I can't believe how easy this recipe is to follow. The results are always delicious!",
        "I made this recipe for a bake sale, and it was a huge hit. Sold out in no time!",
        "The aroma while baking this recipe is heavenly. The taste is even better.",
        "I'm a novice baker, but this recipe made me feel like a pro. Thank you!",
        "I've tried many baking recipes, but this one takes the cake. It's simply outstanding.",
        "I made a few modifications to this recipe, and it turned out fantastic. So versatile!",
        "This recipe is foolproof. I've never had a baking fail with it.",
        "I love how detailed the instructions are in this recipe. Makes it easy to follow.",
        "I baked this recipe for a family gathering, and it was a crowd-pleaser. Everyone loved it!",
        "I'm always looking for new baking recipes, and this one exceeded my expectations.",
        "I'm not usually a fan of baking, but this recipe made it enjoyable. Delicious results!",
        "I followed this recipe exactly as written, and it turned out perfect. So tasty!",
        "This recipe has become a staple in my baking repertoire. Highly recommend it.",
        "I made this recipe with my kids, and it was a fun and delicious activity. Great for bonding!",
        "The texture of this baked treat is spot on. So light and fluffy!",
        "I can't wait to make this recipe again. It's a definite crowd-pleaser.",
        "I never thought I could replicate my favorite bakery goods, but this recipe did it!",
        "I made a double batch of this recipe, and it disappeared within minutes. A true hit!",
        "The flavors in this recipe are divine. It's like a party in my mouth!",
        "I made this recipe for a special occasion, and it was the highlight of the event.",
        "This recipe is a hidden gem. It deserves more recognition. Absolutely delicious!",
        "I'm already planning to bake this recipe again next week. It's that good!",
        "I made this recipe for my friends, and they were impressed. Thanks for the recipe!",
        "The step-by-step instructions in this recipe made it foolproof. Thank you!",
        "I love how versatile this recipe is. You can easily customize it to your liking.",
        "This recipe is a time-saver. I appreciate how quick and easy it is to prepare.",
        "I made this recipe for a bake-off, and it won first prize. I'm thrilled!",
        "The flavors in this recipe are so rich and decadent. It's pure indulgence.",
        "I made this recipe for my vegan friends, and they absolutely loved it. A big win!",
        "I'm not a skilled baker, but this recipe made me feel like one. Foolproof and delicious!",
        "I made this recipe with my kids, and it was a fun and tasty baking adventure.",
        "The presentation of this baked treat is impressive. It looks as good as it tastes!",
        "I can't resist the temptation to bake this recipe over and over again. So addictive!",
        "I made this recipe for a potluck, and it received rave reviews. Empty plates all around!",
        "I'm always looking for healthier baking options, and this recipe fits the bill. Delicious and guilt-free!",
        "I tried this recipe with a twist, and it turned out amazing. So versatile!",
        "I made this recipe for a baking competition, and it won me first place. Thanks for sharing!",
        "The combination of flavors in this recipe is unique and delightful. A true culinary masterpiece.",
        "I made this recipe for my family, and they couldn't get enough of it. It's now a family favorite.",
        "This recipe is a game-changer. I've never had a baked treat like this before. Simply sensational!",
        "I'm not a fan of baking, but this recipe has changed my perspective. It's fun and rewarding!",
        "I made this recipe for a birthday party, and it was a hit. The kids loved it!",
        "The crust on this baked good is perfection. Crispy on the outside, soft on the inside.",
        "I can't believe I've been missing out on this recipe. It's a new favorite for sure.",
        "I made this recipe for a bake sale, and it sold like hotcakes. I had to make more!",
        "The texture of this baked treat is heavenly. It's like biting into a cloud!",
        "I'm a fan of all things chocolate, and this recipe satisfied my cravings. Pure bliss!",
        "I made this recipe for a brunch gathering, and it was a huge hit. Everyone asked for the recipe.",
        "This recipe is a must-try for all baking enthusiasts. It's a real showstopper!",
        "I love the simplicity of this recipe. Few ingredients, but the flavor is incredible.",
        "I baked this recipe for a charity event, and it was a success. Money raised and smiles on faces!",
        "The secret ingredient in this recipe is genius. It takes the flavor to a whole new level!",
        "I can't stop recommending this recipe to all my friends. It's foolproof and oh-so-delicious!",
        "I made this recipe for a tea party, and it was the perfect accompaniment to a cup of tea.",
        "This recipe is a real winner. It's earned a permanent spot in my recipe collection.",
        "I'm not a skilled baker, but this recipe made me feel like one. So proud of my baking skills!",
        "I made this recipe with my grandmother, and it brought back fond memories. Truly nostalgic.",
        "The icing on this baked good is out of this world. It's the perfect finishing touch!",
        "I can't believe how moist and tender this baked treat is. It's perfection in every bite.",
        "I made this recipe for my colleagues, and they were blown away. It's better than store-bought!",
        "This recipe is perfect for special occasions. It's an instant crowd-pleaser.",
        "I'm always looking for gluten-free baking recipes, and this one is a gem. Absolutely delicious!",
        "I tried this recipe with my own twist, and it turned out amazing. So customizable!",
        "I made this recipe for a bake-off, and it won me second place. I'm over the moon!",
        "The aroma that fills the house while baking this recipe is irresistible. Pure happiness!",
        "I can't wait to make this recipe again. It's a family favorite now!",
        "I made this recipe for a baby shower, and it was the highlight of the dessert table.",
        "The crumb of this baked good is perfect. Moist, tender, and full of flavor.",
        "I'm a chocoholic, and this recipe satisfies all my chocolate cravings. So decadent!",
        "I made this recipe for a holiday gathering, and it was a hit. Festive and delicious!",
        "This recipe is a time-saver. Quick to prepare, but the taste is incredible.",
        "I made this recipe with my kids, and they had so much fun. Baking memories in the making!",
        "The glaze on this baked treat is to die for. It adds the perfect touch of sweetness.",
        "I brought this recipe to a potluck, and it was the first to disappear. Everyone loved it!",
        "I'm always looking for healthier dessert options, and this recipe is a winner. Guilt-free indulgence!",
        "I tried this recipe for the first time, and it's already become a favorite. So addictive!",
        "I made this recipe for a bake sale, and it raised a significant amount of money. Mission accomplished!",
        "The balance of flavors in this baked good is spot on. It's a taste sensation!",
        "I can't resist the temptation to have another slice. This recipe is a slice of heaven!",
        "I made this recipe for a bridal shower, and it received so many compliments. Elegant and delicious!",
        "The crust on this pie is perfection. Golden and flaky, just like it should be.",
        "I can't believe how easy this recipe is to make. Foolproof and delicious!",
        "I made this recipe for a dinner party, and it was the perfect finale. Memorable and delightful!",
        "This recipe is a true classic. It's stood the test of time for a reason.",
        "I'm not a natural baker, but this recipe made me feel like one. It's a confidence booster!",
        "I made this recipe with my kids, and it was a joyous baking adventure. Precious memories!",
        "The glaze on this cake is drool-worthy. It adds a burst of flavor and elegance.",
        "I brought this recipe to a potluck, and everyone asked for the recipe. A sure sign of success!",
        "I'm always looking for vegan baking options, and this recipe is a gem. So delicious!",
        "I tried this recipe for the first time, and it exceeded my expectations. A new favorite for sure!",
        "I made this recipe for a charity bake sale, and it was a hit. Raised funds for a good cause!",
        "The layers in this baked treat are perfection. Each bite is pure bliss.",
        "I can't get over how moist this cake is. It's the moistest cake I've ever had!",
        "I made this recipe for a birthday celebration, and it was the star of the party.",
        "The aroma of this baked good is intoxicating. It fills the whole house with warmth and sweetness.",
        "I can't wait to share this recipe with all my friends. It's a guaranteed hit!",
        "I made this recipe for a family gathering, and it received rave reviews. Empty plates all around!",
        "I'm always looking for healthier dessert alternatives, and this recipe is a winner. So satisfying!",
        "I tried this recipe with a twist, and it turned out amazing. So versatile!",
        "I made this recipe for a bake-off competition, and it won me third place. Thrilled with the result!",
        "The layers in this cake are perfectly moist and fluffy. It's like a slice of heaven.",
        "I can't resist having a second slice of this baked good. It's simply irresistible!",
        "I made this recipe for a holiday party, and it was the talk of the event. Delicious and festive!",
        "The glaze on this dessert is the perfect finishing touch. It adds a touch of elegance.",
        "I can't believe I've been missing out on this recipe. It's a new favorite for sure.",
        "I made this recipe for a bake sale, and it sold like hotcakes. I had to make more!",
        "The texture of this baked treat is heavenly. It's like biting into a cloud!",
        "I'm a fan of all things chocolate, and this recipe satisfied my cravings. Pure bliss!",
        "I made this recipe for a brunch gathering, and it was a huge hit. Everyone asked for the recipe.",
        "This recipe is a must-try for all baking enthusiasts. It's a real showstopper!",
        "I love the simplicity of this recipe. Few ingredients, but the flavor is incredible.",
        "I baked this recipe for a charity event, and it was a success. Money raised and smiles on faces!",
        "The secret ingredient in this recipe is genius. It takes the flavor to a whole new level!",
        "I can't stop recommending this recipe to all my friends. It's foolproof and oh-so-delicious!",
        "I made this recipe for a tea party, and it was the perfect accompaniment to a cup of tea.",
        "This recipe is a real winner. It's earned a permanent spot in my recipe collection.",
        "I'm not a skilled baker, but this recipe made me feel like one. So proud of my baking skills!",
        "I made this recipe with my grandmother, and it brought back fond memories. Truly nostalgic.",
        "The icing on this baked good is out of this world. It's the perfect finishing touch!",
        "I can't believe how moist and tender this baked treat is. It's perfection in every bite.",
        "I made this recipe for my colleagues, and they were blown away. It's better than store-bought!",
        "This recipe is perfect for special occasions. It's an instant crowd-pleaser.",
        "I'm always looking for gluten-free baking recipes, and this one is a gem. Absolutely delicious!",
        "I tried this recipe with my own twist, and it turned out amazing. So customizable!",
        "I made this recipe for a bake-off, and it won me second place. I'm over the moon!",
        "The aroma that fills the house while baking this recipe is irresistible. Pure happiness!",
        "I can't wait to make this recipe again. It's a family favorite now!",
        "I made this recipe for a baby shower, and it was the highlight of the dessert table.",
        "The crumb of this baked good is perfect. Moist, tender, and full of flavor.",
        "I'm a chocoholic, and this recipe satisfies all my chocolate cravings. So decadent!",
        "I made this recipe for a holiday gathering, and it was a hit. Festive and delicious!",
        "This recipe is a time-saver. Quick to prepare, but the taste is incredible.",
        "I made this recipe with my kids, and they had so much fun. Baking memories in the making!",
        "The glaze on this baked treat is to die for. It adds the perfect touch of sweetness.",
        "I brought this recipe to a potluck, and it was the first to disappear. Everyone loved it!",
        "I'm always looking for healthier dessert options, and this recipe is a winner. Guilt-free indulgence!",
        "I tried this recipe for the first time, and it's already become a favorite. So addictive!",
        "I made this recipe for a bake sale, and it raised a significant amount of money. Mission accomplished!",
        "The balance of flavors in this baked good is spot on. It's a taste sensation!",
        "I can't resist the temptation to have another slice. This recipe is a slice of heaven!",
        "I made this recipe for a bridal shower, and it received so many compliments. Elegant and delicious!",
        "The crust on this pie is perfection. Golden and flaky, just like it should be.",
        "I can't believe how easy this recipe is to make. Foolproof and delicious!",
        "I made this recipe for a dinner party, and it was the perfect finale. Memorable and delightful!",
        "This recipe is a true classic. It's stood the test of time for a reason.",
        "I'm not a natural baker, but this recipe made me feel like one. It's a confidence booster!",
        "I made this recipe with my kids, and it was a joyous baking adventure. Precious memories!",
        "The glaze on this cake is drool-worthy. It adds a burst of flavor and elegance.",
        "I brought this recipe to a potluck, and everyone asked for the recipe. A sure sign of success!",
        "I'm always looking for vegan baking options, and this recipe is a gem. So delicious!",
        "I tried this recipe for the first time, and it exceeded my expectations. A new favorite for sure!",
        "I made this recipe for a charity bake sale, and it was a hit. Raised funds for a good cause!",
        "The layers in this baked treat are perfection. Each bite is pure bliss.",
        "I can't get over how moist this cake is. It's the moistest cake I've ever had!",
        "I made this recipe for a birthday celebration, and it was the star of the party.",
        "The aroma of this baked good is intoxicating. It fills the whole house with warmth and sweetness.",
        "I can't wait to share this recipe with all my friends. It's a guaranteed hit!",
        "I made this recipe for a family gathering, and it received rave reviews. Empty plates all around!",
        "I'm always looking for healthier dessert alternatives, and this recipe is a winner. So satisfying!",
        "I tried this recipe with a twist, and it turned out amazing. So versatile!",
        "I made this recipe for a bake-off competition, and it won me third place. Thrilled with the result!",
        "The layers in this cake are perfectly moist and fluffy. It's like a slice of heaven.",
        "I can't resist having a second slice of this baked good. It's simply irresistible!",
        "I made this recipe for a holiday party, and it was the talk of the event. Delicious and festive!",
        "The glaze on this dessert is the perfect finishing touch. It adds a touch of elegance.",
        "I can't believe I've been missing out on this recipe. It's a new favorite for sure.",
        "I made this recipe for a bake sale, and it sold like hotcakes. I had to make more!",
        "The aroma while baking this recipe is heavenly. The taste is even better.",
        "I'm a novice baker, but this recipe made me feel like a pro. Thank you!",
        "I've tried many baking recipes, but this one takes the cake. It's simply outstanding.",
        "I made a few modifications to this recipe, and it turned out fantastic. So versatile!",
        "This recipe is foolproof. I've never had a baking fail with it.",
        "I love how detailed the instructions are in this recipe. Makes it easy to follow.",
        "I baked this recipe for a family gathering, and it was a crowd-pleaser. Everyone loved it!",
        "I'm always looking for new baking recipes, and this one exceeded my expectations.",
        "I'm not usually a fan of baking, but this recipe made it enjoyable. Delicious results!",
        "I followed this recipe exactly as written, and it turned out perfect. So tasty!",
        "This recipe has become a staple in my baking repertoire. It never disappoints.",
        "I made this recipe for a school event, and the kids couldn't get enough of it.",
        "I've made this recipe multiple times now, and it's a hit every time. Can't get enough!",
        "I love how the ingredients in this recipe come together. The flavor is incredible.",
        "I made this recipe for a baking competition, and it won me first place. Thanks for sharing!",
        "The combination of flavors in this recipe is unique and delightful. A true culinary masterpiece.",
        "I made this recipe for my family, and they couldn't get enough of it. It's now a family favorite.",
        "This recipe is a game-changer. I've never had a baked treat like this before. Simply sensational!",
        "I'm not a fan of baking, but this recipe has changed my perspective. It's fun and rewarding!",
        "I made this recipe for a birthday party, and it was a hit. The kids loved it!",
        "The crust on this baked good is perfection. Crispy on the outside, soft on the inside.",
        "I can't believe I've been missing out on this recipe. It's a new favorite for sure.",
        "I made this recipe for a bake sale, and it sold like hotcakes. I had to make more!",
        "The texture of this baked treat is heavenly. It's like biting into a cloud!",
        "I'm a fan of all things chocolate, and this recipe satisfied my cravings. Pure bliss!",
        "I made this recipe for a brunch gathering, and it was a huge hit. Everyone asked for the recipe.",
        "This recipe is a must-try for all baking enthusiasts. It's a real showstopper!",
        "I love the simplicity of this recipe. Few ingredients, but the flavor is incredible.",
        "I baked this recipe for a charity event, and it was a success. Money raised and smiles on faces!",
        "The secret ingredient in this recipe is genius. It takes the flavor to a whole new level!",
        "I can't stop recommending this recipe to all my friends. It's foolproof and oh-so-delicious!",
        "I made this recipe for a tea party, and it was the perfect accompaniment to a cup of tea.",
        "This recipe is a real winner. It's earned a permanent spot in my recipe collection.",
        "I'm not a skilled baker, but this recipe made me feel like one. So proud of my baking skills!",
        "I made this recipe with my grandmother, and it brought back fond memories. Truly nostalgic.",
        "The icing on this baked good is out of this world. It's the perfect finishing touch!",
        "I can't believe how moist and tender this baked treat is. It's perfection in every bite.",
        "I made this recipe for my colleagues, and they were blown away. It's better than store-bought!",
        "This recipe is perfect for special occasions. It's an instant crowd-pleaser.",
        "I'm always looking for gluten-free baking recipes, and this one is a gem. Absolutely delicious!",
        "I tried this recipe with my own twist, and it turned out amazing. So customizable!",
        "I made this recipe for a bake-off, and it won me second place. I'm over the moon!",
        "The aroma that fills the house while baking this recipe is irresistible. Pure happiness!",
        "I can't wait to make this recipe again. It's a family favorite now!",
        "I made this recipe for a baby shower, and it was the highlight of the dessert table.",
        "The crumb of this baked good is perfect. Moist, tender, and full of flavor.",
        "I'm a chocoholic, and this recipe satisfies all my chocolate cravings. So decadent!",
        "I made this recipe for a holiday gathering, and it was a hit. Festive and delicious!",
        "This recipe is a time-saver. Quick to prepare, but the taste is incredible.",
        "I made this recipe with my kids, and they had so much fun. Baking memories in the making!",
        "The glaze on this cake is drool-worthy. It adds a burst of flavor and elegance.",
        "I brought this recipe to a potluck, and everyone asked for the recipe. A sure sign of success!",
        "I'm always looking for vegan baking options, and this recipe is a gem. So delicious!",
        "I tried this recipe for the first time, and it exceeded my expectations. A new favorite for sure!",
        "I made this recipe for a charity bake sale, and it was a hit. Raised funds for a good cause!",
        "The layers in this baked treat are perfection. Each bite is pure bliss.",
        "I can't get over how moist this cake is. It's the moistest cake I've ever had!",
        "I made this recipe for a birthday celebration, and it was the star of the party.",
        "The aroma of this baked good is intoxicating. It fills the whole house with warmth and sweetness.",
        "I can't wait to share this recipe with all my friends. It's a guaranteed hit!",
        "I made this recipe for a family gathering, and it received rave reviews. Empty plates all around!",
        "I'm always looking for healthier dessert alternatives, and this recipe is a winner. So satisfying!",
        "I tried this recipe with a twist, and it turned out amazing. So versatile!",
        "I made this recipe for a bake-off competition, and it won me third place. Thrilled with the result!",
        "The layers in this cake are perfectly moist and fluffy. It's like a slice of heaven.",
        "I can't resist having a second slice of this baked good. It's simply irresistible!",
        "I made this recipe for a holiday party, and it was the talk of the event. Delicious and festive!",
        "The glaze on this dessert is the perfect finishing touch. It adds a touch of elegance.",
        "I can't believe I've been missing out on this recipe. It's a new favorite for sure.",
        "I made this recipe for a bake sale, and it sold like hotcakes. I had to make more!",
        "The aroma while baking this recipe is heavenly. The taste is even better.",
        "I'm a novice baker, but this recipe made me feel like a pro. Thank you!",
        "I've tried many baking recipes, but this one takes the cake. It's simply outstanding.",
        "I made a few modifications to this recipe, and it turned out fantastic. So versatile!",
        "This recipe is foolproof. I've never had a baking fail with it.",
        "I love how detailed the instructions are in this recipe. Makes it easy to follow.",
        "I baked this recipe for a family gathering, and it was a crowd-pleaser. Everyone loved it!",
        "I'm always looking for new baking recipes, and this one exceeded my expectations.",
        "I'm not usually a fan of baking, but this recipe made it enjoyable. Delicious results!",
        "I followed this recipe exactly as written, and it turned out perfect. So tasty!",
        "This recipe has become a staple in my baking repertoire. It never disappoints.",
        "I made this recipe for a school event, and the kids couldn't get enough of it.",
        "I've made this recipe multiple times now, and it's a hit every time. Can't get enough!",
        "I love how the ingredients in this recipe come together. The flavor is incredible.",
        "I made this recipe for a baking competition, and it won me first place. Thanks for sharing!",
        "The combination of flavors in this recipe is unique and delightful. A true culinary masterpiece.",
        "I made this recipe for my family, and they couldn't get enough of it. It's now a family favorite.",
        "This recipe is a game-changer. I've never had a baked treat like this before. Simply sensational!",
        "I'm not a fan of baking, but this recipe has changed my perspective. It's fun and rewarding!",
        "I made this recipe for a birthday party, and it was a hit. The kids loved it!",
        "The crust on this baked good is perfection. Crispy on the outside, soft on the inside.",
        "I can't believe I've been missing out on this recipe. It's a new favorite for sure.",
        "I made this recipe for a bake sale, and it sold like hotcakes. I had to make more!",
        "The texture of this baked treat is heavenly. It's like biting into a cloud!",
        "I'm a fan of all things chocolate, and this recipe satisfied my cravings. Pure bliss!",
        "I made this recipe for a brunch gathering, and it was a huge hit. Everyone asked for the recipe.",
        "This recipe is a must-try for all baking enthusiasts. It's a real showstopper!",
        "I love the simplicity of this recipe. Few ingredients, but the flavor is incredible.",
        "I baked this recipe for a charity event, and it was a success. Money raised and smiles on faces!",
        "The secret ingredient in this recipe is genius. It takes the flavor to a whole new level!",
        "I can't stop recommending this recipe to all my friends. It's foolproof and oh-so-delicious!",
        "I made this recipe for a tea party, and it was the perfect accompaniment to a cup of tea.",
        "This recipe is a real winner. It's earned a permanent spot in my recipe collection.",
        "I'm not a skilled baker, but this recipe made me feel like one. So proud of my baking skills!",
        "I made this recipe with my grandmother, and it brought back fond memories. Truly nostalgic.",
        "The icing on this baked good is out of this world. It's the perfect finishing touch!",
        "I can't believe how moist and tender this baked treat is. It's perfection in every bite.",
        "I made this recipe for my colleagues, and they were blown away. It's better than store-bought!",
        "This recipe is perfect for special occasions. It's an instant crowd-pleaser.",
        "I'm always looking for gluten-free baking recipes, and this one is a gem. Absolutely delicious!",
        "I tried this recipe with my own twist, and it turned out amazing. So customizable!",
        "I made this recipe for a bake-off, and it won me second place. I'm over the moon!",
        "The aroma that fills the house while baking this recipe is irresistible. Pure happiness!",
        "I can't wait to make this recipe again. It's a family favorite now!",
        "I made this recipe for a baby shower, and it was the highlight of the dessert table.",
        "The crumb of this baked good is perfect. Moist, tender, and full of flavor.",
        "I'm a chocoholic, and this recipe satisfies all my chocolate cravings. So decadent!",
        "This recipe is amazing! It's now my go-to for family gatherings.",
        "I can't believe how easy this recipe is to make. Delicious and hassle-free!",
        "I added a twist to this recipe by incorporating some spices, and it turned out fantastic!",
        "My kids loved this dish! Finally, a recipe they'll happily eat.",
        "The flavors in this recipe are so well-balanced. It's a true culinary delight.",
        "I made this recipe for a dinner party, and everyone was impressed. Thank you!",
        "I'm a novice cook, but I was able to nail this recipe. So proud of myself!",
        "I've tried many recipes, but this one takes the cake. It's simply outstanding.",
        "I made a few adjustments to suit my dietary preferences, and the result was fantastic!",
        "This recipe is a game-changer. It's now a staple in my kitchen.",
        "I never thought I could make something this delicious. This recipe proved me wrong!",
        "I've shared this recipe with all my friends. It's too good not to be shared!",
        "The aroma while cooking this recipe was heavenly. The taste was even better.",
        "I made this recipe for a potluck, and it was a huge hit. Empty plates all around!",
        "I'm always looking for new recipes to try, and this one exceeded my expectations.",
        "I'm not usually a fan of cooking, but this recipe made it enjoyable. Thank you!",
        "I followed the recipe exactly as written, and the result was perfection. Yum!",
        "This recipe brought back childhood memories. It's comfort food at its best.",
        "I made this recipe for my partner's birthday, and they absolutely loved it.",
        "The presentation of this dish is restaurant-worthy. I felt like a professional chef!",
        "I can't wait to make this recipe again. It's a definite crowd-pleaser.",
        "I never thought I could replicate my favorite restaurant dish, but this recipe did it!",
        "I made a double batch of this recipe, and it disappeared within minutes. So good!",
        "The ingredients in this recipe complement each other perfectly. Well done!",
        "I'm a picky eater, but I couldn't resist trying this recipe. I'm glad I did!",
        "I made this recipe for a special occasion, and it was the highlight of the event.",
        "This recipe is a hidden gem. It deserves more recognition. Absolutely delicious!",
        "I'm already planning to make this recipe again next week. It's that good!",
        "I made this recipe for my parents, and they were impressed. Thanks for the recipe!",
        "The step-by-step instructions in this recipe made it foolproof. Thank you!",
        "I love how versatile this recipe is. You can easily customize it to your liking.",
        "This recipe is a time-saver. I appreciate how quick and easy it is to prepare.",
        "I made this recipe for a dinner date, and it was a hit. We're both impressed!",
        "The flavors in this recipe are so rich and vibrant. It's a true culinary masterpiece.",
        "I made this recipe for my vegan friends, and they absolutely loved it. A big win!",
        "I'm not a skilled cook, but this recipe made me feel like one. It's foolproof!",
        "I made this recipe with my kids, and it was a fun and delicious bonding activity.",
        "The texture of this dish is spot on. I can't get enough of it!",
        "I'm always looking for healthy recipes, and this one ticks all the boxes. So tasty!",
        "I made this recipe for a potluck, and it received so many compliments. Success!",
        "I can't believe I've been missing out on this recipe. It's a new favorite for sure.",
        "The flavors in this recipe are perfectly balanced. I'll be making this again soon.",
        "I made this recipe for my partner, who is a picky eater, and they loved it. Thank you!",
        "This recipe is a real crowd-pleaser. It disappeared in no time!",
        "I'm not a fan of cooking, but this recipe made it enjoyable. Simple yet delicious!",
        "I tried this recipe with a twist, and it turned out amazing. So versatile!",
        "I made this recipe for a girls' night, and it was a hit. We all wanted the recipe.",
        "The combination of ingredients in this recipe is unique and delightful. Love it!",
        "I made this recipe for my family, and they couldn't stop raving about it. Success!",
    ]
    print('INSERT INTO comments VALUES ')
    for comment in comments:
        coma = ''
        if comment != comments[-1]:
            coma = ','
        print('(DEFAULT, ' + str(random.randint(1, 103)) + ', ' + str(random.randint(1, 363)) + ', \'null\', \'' + comment + '\')' + coma)
    print(';')

    print('INSERT INTO users_liked_comments VALUES ')
    for i in range(1, 150):
        users = list(range(1, 360))
        n = random.randint(1, 50)
        for j in range(n):
            user = random.choice(users)
            users.remove(user)
            coma = ''
            if i != 149 or j != n-1:
                coma = ','
            print('(' + str(i) + ', ' + str(user) + ')' + coma)
    print(';')
